services:
  - type: web
    name: StoreFront
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn storefront.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: storefront
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      -key: DJANGO_SETTINGS_MODULE
        value: storefront.settings.prod